resource:
  properties:
    type:
      description: ShipmentNote
      example: ShipmentNote

attributes:
  allOf:
    - $ref: '#/note/message'
    - $ref: '#/note/authorId'
    - $ref: '#/dataTypes/createdAt'

relationships:
  type: object
  description: Shipment Relation for this resource
  properties:
    shipment:
      type: object
      description: Shipment associated with this note
      properties:
        data:
          allOf:
            - $ref: '#/shipments/resource'
            - $ref: '#/dataTypes/resourceId'

getResource:
  allOf:
    - $ref: '#/resource'
    - properties:
        attributes:
          $ref: '#/attributes'
        relationships:
          $ref: '#/relationships'

getResponse:
  allOf:
    - $ref: '#/jsonApi/data'
    - properties:
        data:
          $ref: '#/getResource'


createResponse:
  allOf:
    - $ref: '#/jsonApi/data'
    - properties:
        data:
          $ref: '#/getResource'
#    - properties:
#        data:
#          properties:
#            meta:
#              $ref: '#/document/presignedS3Post'

listResponse:
  allOf:
    - $ref: '#/jsonApi/dataArray'
    - $ref: '#/jsonApi/linksAndMeta'
    - properties:
        data:
          items:
            $ref: '#/getResource'
#    - properties:
#        data:
#          items:
#            properties:
#              meta:
#                oneOf:
#                - $ref: '#/document/presignedS3Post'
#                - $ref: '#/document/presignedS3Get'

note:
  $ref: dataTypes.yaml

shipments:
  $ref: ../shipments/schema.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
