# Generated by Django 2.2.4 on 2019-09-19 17:17

import apps.eth.fields
import apps.jobs.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
from shipchain_common.utils import random_id


class Migration(migrations.Migration):

    replaces = [('jobs', '0001_initial'), ('jobs', '0002_auto_20180730_1547'), ('jobs', '0003_auto_20180801_1626'), ('jobs', '0004_auto_20180829_2114'), ('jobs', '0005_asyncjob_listeners'), ('jobs', '0006_auto_20180830_1352'), ('jobs', '0007_asyncjob_wallet_lock_token'), ('jobs', '0008_auto_20180918_1640'), ('jobs', '0009_asyncaction'), ('jobs', '0010_nullable_gm2m'), ('jobs', '0011_gm2m_to_fk_data'), ('jobs', '0012_gm2m_to_fk_cleanup')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shipments', '0037_set_initial_historical_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.CharField(default=random_id, max_length=36, primary_key=True, serialize=False)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', enumfields.fields.EnumIntegerField(default=0, enum=apps.jobs.models.JobState)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment'))
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=random_id, max_length=36, primary_key=True, serialize=False)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('async_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.AsyncJob')),
                ('type', enumfields.fields.EnumIntegerField(enum=apps.jobs.models.MessageType)),
            ],
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='wallet_lock_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='last_try',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='AsyncAction',
            fields=[
                ('id', models.CharField(default=random_id, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('action_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.jobs.models.AsyncActionType)),
                ('vault_hash', apps.eth.fields.HashField(blank=True, default='', max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('async_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='jobs.AsyncJob')),
            ],
            options={
                'ordering': ('created_at',),
            },
        )
    ]
