# Generated by Django 3.0.8 on 2020-10-08 22:10

import apps.eth.fields
import apps.jobs.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import enumfields.fields
import shipchain_common.utils


class Migration(migrations.Migration):

    replaces = [('jobs', '0001_squashed_091919'), ('jobs', '0002_asyncjob_data_migration')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.CharField(default=shipchain_common.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', enumfields.fields.EnumIntegerField(default=0, enum=apps.jobs.models.JobState)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
                ('wallet_lock_token', models.CharField(blank=True, max_length=32, null=True)),
                ('delay', models.IntegerField(default=0)),
                ('last_try', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=shipchain_common.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('async_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.AsyncJob')),
                ('type', enumfields.fields.EnumIntegerField(enum=apps.jobs.models.MessageType)),
            ],
        ),
        migrations.CreateModel(
            name='AsyncAction',
            fields=[
                ('id', models.CharField(default=shipchain_common.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('action_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.jobs.models.AsyncActionType)),
                ('vault_hash', apps.eth.fields.HashField(blank=True, default='', max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('async_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='jobs.AsyncJob')),
            ],
            options={
                'ordering': ('created_at',),
            },
        )
    ]
