# Generated by Django 2.0.7 on 2018-07-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobListener',
            new_name='Listener',
        ),
        migrations.RenameModel(
            old_name='JobMessage',
            new_name='Message',
        ),
    ]
