# Generated by Django 2.0.7 on 2018-08-01 16:26

import apps.jobs.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180730_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncjob',
            name='state',
            field=enumfields.fields.EnumIntegerField(default=0, enum=apps.jobs.models.JobState),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=apps.jobs.models.MessageType),
            preserve_default=False,
        ),
    ]
