# Generated by Django 2.0.7 on 2018-08-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0003_auto_20180801_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_id', models.CharField(max_length=36)),
                ('async_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.AsyncJob')),
                ('listener_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='listener',
            name='async_job',
        ),
        migrations.RemoveField(
            model_name='listener',
            name='listener_type',
        ),
        migrations.DeleteModel(
            name='Listener',
        ),
    ]
