# Generated by Django 2.0.7 on 2018-08-30 13:30

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0004_auto_20180829_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncjob',
            name='listeners',
            field=gm2m.fields.GM2MField(through='jobs.JobListener', through_fields=['async_job', 'listener', 'listener_type', 'listener_id']),
        ),
    ]
