# Generated by Django 2.0.7 on 2018-08-30 13:52

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_asyncjob_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncjob',
            name='listeners',
            field=gm2m.fields.GM2MField('shipments.Shipment', through='jobs.JobListener', through_fields=['async_job', 'listener', 'listener_type', 'listener_id']),
        ),
    ]
