# Generated by Django 2.0.7 on 2018-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180830_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncjob',
            name='wallet_lock_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
