# Generated by Django 2.1.7 on 2019-06-20 19:49

import django.db.models.deletion
import gm2m.fields
from django.db import migrations, models
from gm2m.deletion import DO_NOTHING


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0037_set_initial_historical_objects'),
        ('jobs', '0009_asyncaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncjob',
            name='listeners',
            field=gm2m.fields.GM2MField('shipments.Shipment', through='jobs.JobListener',
                                        through_fields=['async_job', 'listener', 'listener_type', 'listener_id'],
                                        null=True, on_delete=DO_NOTHING),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment', null=True,
                                    default=None),
            preserve_default=False,
        ),
    ]
