trackingDataResource:
  properties:
    type:
      description: TrackingData
      example: TrackingData

included:
  type: array
  items:
    anyOf:
      - $ref: '#/includedResource'

attributes:
  allOf:
    - $ref: '#/overview/location'


includedAttributes:
  allOf:
    - $ref: '#/shipment/state'
    - $ref: '#/shipment/exception'
    - $ref: '#/shipment/delayed'

listResponse:
  allOf:
    - $ref: '#/jsonApi/dataArray'
    - $ref: '#/jsonApi/linksAndMeta'
    - properties:
        data:
          items:
            $ref: '#/getResource'
        included:
          $ref: '#/included'

getResource:
  allOf:
    - $ref: '#/trackingDataResource'
    - properties:
        attributes:
          $ref: '#/attributes'
        relationships:
          $ref: '#/relationships'

getIncludedResource:
  allOf:
    - $ref: '../shipments/schema.yaml#/resource'
    - properties:
        attributes:
          $ref: '#/includedAttributes'

includedResource:
  title: Shipment
  description: Shipment light details associated to the resource
  type: object
  allOf:
  - $ref: '#/dataTypes/resourceId'
  - $ref: '#/getIncludedResource'


relationships:
  type: object
  description: Relation for this resource
  properties:
    shipment:
      type: object
      description: Shipment associated with this resource
      properties:
        data:
          allOf:
            - $ref: '../shipments/schema.yaml#/resource'
            - $ref: '#/dataTypes/resourceId'
    device:
      $ref: '#/shipment/device'


overview:
  $ref: dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

shipment:
  $ref: ../shipments/dataTypes.yaml
