# Generated by Django 2.0.9 on 2018-12-11 17:35

import apps.documents.models
import apps.utils
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0019_trackingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=apps.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_id', models.CharField(max_length=36)),
                ('document_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.DocumentType)),
                ('file_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.FileType)),
                ('upload_status', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.UploadStatus)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
            ],
        ),
    ]
