# Generated by Django 2.1.5 on 2019-02-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accessed_from_vault_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='accessed_from_vault_at',
            new_name='accessed_from_vault_on',
        ),
    ]
