# Generated by Django 2.1.7 on 2019-07-09 15:27

import apps.documents.models
import apps.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDocument',
            fields=[
                ('id', models.CharField(default=apps.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_id', models.CharField(max_length=36)),
                ('updated_by', models.CharField(max_length=36)),
                ('csv_file_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.CsvFileType)),
                ('upload_status', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.UploadStatus)),
                ('processing_status', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.ProcessingStatus)),
                ('report', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
