# Generated by Django 2.0.9 on 2018-11-27 16:00

import apps.documents.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.DocumentType),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.FileType),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_status',
            field=enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.UploadStatus),
        ),
    ]
