# Generated by Django 2.1.7 on 2019-07-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('updated_at',)},
        ),
    ]
