# Generated by Django 2.2.4 on 2019-11-07 16:46

import apps.documents.models
import apps.simple_history
import apps.utils
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import shipchain_common.utils
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_use_related_name_for_historical_relation'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.CharField(db_index=True, default=shipchain_common.utils.random_id, max_length=36)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_id', models.CharField(max_length=36)),
                ('document_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.DocumentType)),
                ('file_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.documents.models.FileType)),
                ('upload_status', enumfields.fields.EnumIntegerField(default=0, enum=apps.utils.UploadStatus)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.CharField(blank=True, max_length=36, null=True)),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shipments.HistoricalShipment')),
            ],
            options={
                'verbose_name': 'historical document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model, apps.simple_history.HistoricalChangesMixin),
        ),
    ]
