# Generated by Django 2.1.3 on 2018-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181127_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='s3_path',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
