resource:
  properties:
    type:
      description: Shipment
      example: Shipment

attributes:
  allOf:
  - $ref: '#/shipment/ownerId'
  - $ref: '#/shipment/storageCredentialsId'
  - $ref: '#/shipment/vaultId'
  - $ref: '#/shipment/vaultUri'
  - $ref: '#/shipment/shipperWalletId'
  - $ref: '#/shipment/carrierWalletId'
  - $ref: '#/shipment/moderatorWalletId'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'
  - $ref: '#/shipment/updatedBy'
  - $ref: '#/shipment/carriersScac'
  - $ref: '#/shipment/forwardersScac'
  - $ref: '#/shipment/nvoccScac'
  - $ref: '#/shipment/shippersReference'
  - $ref: '#/shipment/forwardersReference'
  - $ref: '#/shipment/forwardersShipperId'
  - $ref: '#/shipment/carriersInstructions'
  - $ref: '#/shipment/proNumber'
  - $ref: '#/shipment/billMaster'
  - $ref: '#/shipment/billHouse'
  - $ref: '#/shipment/billSubhouse'
  - $ref: '#/shipment/paymentTerms'
  - $ref: '#/shipment/vesselName'
  - $ref: '#/shipment/voyageNumber'
  - $ref: '#/shipment/modeOfTransportCode'
  - $ref: '#/shipment/packageQty'
  - $ref: '#/shipment/weightGross'
  - $ref: '#/shipment/volume'
  - $ref: '#/shipment/containerQty'
  - $ref: '#/shipment/weightDim'
  - $ref: '#/shipment/weightChargeable'
  - $ref: '#/shipment/docsReceivedAct'
  - $ref: '#/shipment/docsApprovedAct'
  - $ref: '#/shipment/pickupAppt'
  - $ref: '#/shipment/pickupEst'
  - $ref: '#/shipment/pickupAct'
  - $ref: '#/shipment/loadingEst'
  - $ref: '#/shipment/loadingAct'
  - $ref: '#/shipment/departureEst'
  - $ref: '#/shipment/departureAct'
  - $ref: '#/shipment/deliveryApptAct'
  - $ref: '#/shipment/portArrivalEst'
  - $ref: '#/shipment/portArrivalAct'
  - $ref: '#/shipment/deliveryEst'
  - $ref: '#/shipment/deliveryAct'
  - $ref: '#/shipment/deliveryAttempt'
  - $ref: '#/shipment/cancelRequestedDateAct'
  - $ref: '#/shipment/cancelConfirmedDateAct'
  - $ref: '#/shipment/customsFiledDateAct'
  - $ref: '#/shipment/customsHoldDateAct'
  - $ref: '#/shipment/customsReleaseDateAct'
  - $ref: '#/shipment/containerType'
  - $ref: '#/shipment/portArrivalLocode'
  - $ref: '#/shipment/finalPortLocode'
  - $ref: '#/shipment/importLocode'
  - $ref: '#/shipment/ladingLocode'
  - $ref: '#/shipment/originLocode'
  - $ref: '#/shipment/usRouted'
  - $ref: '#/shipment/importCustomsMode'
  - $ref: '#/shipment/usExportPort'
  - $ref: '#/shipment/customerFields'
  - $ref: '#/shipment/specialInstructions'
  - $ref: '#/shipment/trailerNumber'
  - $ref: '#/shipment/sealNumber'
  - $ref: '#/shipment/isMasterBOL'
  - $ref: '#/shipment/nmfcClass'
  - $ref: '#/shipment/isHazmat'
  - $ref: '#/shipment/state'
  - $ref: '#/shipment/delayed'
  - $ref: '#/shipment/expectedDelayHours'
  - $ref: '#/shipment/exception'
  - $ref: '#/shipment/gtxRequired'
  - $ref: '#/shipment/assetCustodianId'
  - $ref: '#/shipment/geofences'
  - $ref: '#/shipment/contractVersion'
  - $ref: '#/shipment/aftershipTracking'

meta:
  allOf:
  - $ref: '#/dataTypes/asyncJobId'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'
      relationships:
        $ref: '#/relationships'

getResponse:
  allOf:
  - $ref: '#/jsonApi/data'
  - properties:
      data:
        $ref: '#/getResource'
      included:
        $ref: '#/included'

loadData:
  type: object
  title: load_data
  description: Smart contract data associated with the shipment
  properties:
    load_data:
      $ref: '#/shipment/loadData'

shipToLocation:
  type: object
  title: ship_to_location
  description: ship_to_location associated with the shipment
  properties:
    ship_to_location:
      $ref: '#/shipment/locationData'

shipFromLocation:
  type: object
  title: ship_from_location
  description: ship_from_location associated with the shipment
  properties:
    ship_from_location:
      $ref: '#/shipment/locationData'

finalDestinationLocation:
  type: object
  title: final_destination_location
  description: final_destination_location associated with the shipment
  properties:
    final_destination_location:
      $ref: '#/shipment/locationData'

billToLocation:
  type: object
  title: bill_to_location
  description: bill_to_location associated with the shipment
  properties:
    bill_to_location:
      $ref: '#/shipment/locationData'

device:
  type: object
  title: device
  description: device associated with the shipment
  properties:
    device:
      $ref: '#/shipment/device'

shipmentTags:
  type: object
  description: Relations for this resource
  properties:
    tags:
      title: tags
      type: object
      description: Tags associated with the Shipment
      properties:
        meta:
          type: object
          title: meta
          properties:
            count:
              title: count
              description: Number of Tags associated with the Shipment
              type: number
              format: integer
              example: 3
        data:
          type: array
          items:
            type: object
            allOf:
              - $ref: '#/shipmentTag/resource'
              - $ref: '#/dataTypes/resourceId'

relationships:
  type: object
  description: Relations for this resource
  allOf:
  - $ref: '#/loadData'
  - $ref: '#/shipToLocation'
  - $ref: '#/shipFromLocation'
  - $ref: '#/finalDestinationLocation'
  - $ref: '#/billToLocation'
  - $ref: '#/device'
  - $ref: '#/shipmentTags'

createAttributes:
  allOf:
  - $ref: '#/shipment/storageCredentialsId'
  - $ref: '#/shipment/ownerId'
  - $ref: '#/shipment/vaultId'
  - $ref: '#/shipment/vaultUri'
  - $ref: '#/shipment/shipperWalletId'
  - $ref: '#/shipment/carrierWalletId'
  - $ref: '#/shipment/moderatorWalletId'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'
  - $ref: '#/shipment/updatedBy'
  - $ref: '#/shipment/carriersScac'
  - $ref: '#/shipment/forwardersScac'
  - $ref: '#/shipment/nvoccScac'
  - $ref: '#/shipment/shippersReference'
  - $ref: '#/shipment/forwardersReference'
  - $ref: '#/shipment/forwardersShipperId'
  - $ref: '#/shipment/carriersInstructions'
  - $ref: '#/shipment/proNumber'
  - $ref: '#/shipment/billMaster'
  - $ref: '#/shipment/billHouse'
  - $ref: '#/shipment/billSubhouse'
  - $ref: '#/shipment/paymentTerms'
  - $ref: '#/shipment/vesselName'
  - $ref: '#/shipment/voyageNumber'
  - $ref: '#/shipment/modeOfTransportCode'
  - $ref: '#/shipment/packageQty'
  - $ref: '#/shipment/weightGross'
  - $ref: '#/shipment/volume'
  - $ref: '#/shipment/containerQty'
  - $ref: '#/shipment/weightDim'
  - $ref: '#/shipment/weightChargeable'
  - $ref: '#/shipment/docsReceivedAct'
  - $ref: '#/shipment/docsApprovedAct'
  - $ref: '#/shipment/pickupAppt'
  - $ref: '#/shipment/pickupEst'
  - $ref: '#/shipment/pickupAct'
  - $ref: '#/shipment/loadingEst'
  - $ref: '#/shipment/loadingAct'
  - $ref: '#/shipment/departureEst'
  - $ref: '#/shipment/departureAct'
  - $ref: '#/shipment/deliveryApptAct'
  - $ref: '#/shipment/portArrivalEst'
  - $ref: '#/shipment/portArrivalAct'
  - $ref: '#/shipment/deliveryEst'
  - $ref: '#/shipment/deliveryAct'
  - $ref: '#/shipment/deliveryAttempt'
  - $ref: '#/shipment/cancelRequestedDateAct'
  - $ref: '#/shipment/cancelConfirmedDateAct'
  - $ref: '#/shipment/customsFiledDateAct'
  - $ref: '#/shipment/customsHoldDateAct'
  - $ref: '#/shipment/customsReleaseDateAct'
  - $ref: '#/shipment/containerType'
  - $ref: '#/shipment/portArrivalLocode'
  - $ref: '#/shipment/finalPortLocode'
  - $ref: '#/shipment/importLocode'
  - $ref: '#/shipment/ladingLocode'
  - $ref: '#/shipment/originLocode'
  - $ref: '#/shipment/usRouted'
  - $ref: '#/shipment/importCustomsMode'
  - $ref: '#/shipment/usExportPort'
  - $ref: '#/shipment/customerFields'
  - $ref: '#/shipment/specialInstructions'
  - $ref: '#/shipment/trailerNumber'
  - $ref: '#/shipment/sealNumber'
  - $ref: '#/shipment/isMasterBOL'
  - $ref: '#/shipment/nmfcClass'
  - $ref: '#/shipment/isHazmat'
  - $ref: '#/shipment/exception'
  - $ref: '#/shipment/contractVersion'

createResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/createAttributes'
      relationships:
        $ref: '#/relationships'
      meta:
        $ref: '#/meta'

createResponse:
  allOf:
  - $ref: '#/getResponse'
  - properties:
      data:
        properties:
          meta:
            $ref: '#/meta'

included:
  type: array
  items:
    anyOf:
    - $ref: '#/loadShipment/includedResource'
    - $ref: '#/location/includedResource'
    - $ref: '#/includedTagResource'

listResponse:
  allOf:
  - $ref: '#/jsonApi/dataArray'
  - $ref: '#/jsonApi/linksAndMeta'
  - properties:
      data:
        items:
          $ref: '#/getResource'
      included:
        $ref: '#/included'

includedTagResource:
  title: Shipment Tag
  description: Tag associated to the resource
  type: object
  allOf:
    - $ref: '#/dataTypes/resourceId'
    - $ref: '#/shipmentTag/resource'
    - properties:
        attributes:
          $ref: '#/shipmentTag/attributes'
    - properties:
        relationships:
          $ref: '#/shipmentInRelationship'

shipmentInRelationship:
  type: object
  description: Relationships for this resource
  properties:
    shipment:
      type: object
      description: Shipment associated with this resource
      properties:
        data:
          allOf:
            - $ref: '#/resource'
            - $ref: '#/dataTypes/resourcePk'

shipment:
  $ref: dataTypes.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

loadShipment:
  $ref: ../loadShipments/schema.yaml

location:
  $ref: ../locations/schema.yaml

messageRef:
  $ref: ../messages/schema.yaml

shipmentTag:
  $ref:  ../shipmentTags/schema.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
