strings:
- &response_401 "Unauthorized"
- &response_429 "Too Many Requests"
- &response_500 "Internal server error"

401:
  allOf:
  - $ref: '#/jsonApi/error'
  - $ref: '#/jsonApi/errorPointer'
  - properties:
      errors:
        items:
          properties:
            detail:
              example: *response_401
            source:
              properties:
                pointer:
                  example: "/data"
            status:
              example: "401"

429:
  allOf:
  - $ref: '#/jsonApi/error'
  - properties:
      errors:
        items:
          properties:
            detail:
              example: *response_429
            status:
              example: "429"

500:
  allOf:
  - $ref: '#/jsonApi/error'
  - properties:
      errors:
        items:
          properties:
            detail:
              example: *response_500
            status:
              example: "500"

json401:
  type: object
  properties:
    detail:
      example: *response_401

jsonApi:
  $ref: ../jsonApi/schema.yaml
