resource:
  properties:
    type:
      description: Location
      example: Location

geometry:
  properties:
    geometry:
      type: object
      title: geometry
      properties:
        type:
          $ref: '#/location/type/properties/type'
        coordinates:
          $ref: '#/location/coordinates/properties/coordinates'

attributes:
  allOf:
  - $ref: '#/location/name'
  - $ref: '#/location/address_1'
  - $ref: '#/location/address_2'
  - $ref: '#/location/city'
  - $ref: '#/location/state'
  - $ref: '#/location/country'
  - $ref: '#/location/postalCode'
  - $ref: '#/location/phoneNumber'
  - $ref: '#/location/faxNumber'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'
  - $ref: '#/geometry'

includedResource:
  title: Location
  description: Location associated with the resource
  type: object
  allOf:
  - $ref: '#/dataTypes/resourceId'
  - $ref: '#/getResource'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'

permissionLinks:
  $ref: ../permissionLinks/dataTypes.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

location:
  $ref: dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
