# Generated by Django 2.0.7 on 2018-08-15 14:42

import apps.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractReceipt',
            fields=[
                ('block_hash', models.CharField(max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('block_number', models.BigIntegerField()),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('cumulative_gas_used', models.IntegerField()),
                ('from_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('gas_used', models.IntegerField()),
                ('logs', django_extensions.db.fields.json.JSONField(default=dict)),
                ('logs_bloom', models.CharField(max_length=514)),
                ('status', models.BooleanField()),
                ('to_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('transaction_hash', models.CharField(max_length=66, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('transaction_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=apps.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('block_number', models.BigIntegerField()),
                ('transaction_hash', models.CharField(max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('transaction_index', models.IntegerField()),
                ('block_hash', models.CharField(max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('log_index', models.IntegerField()),
                ('removed', models.BooleanField()),
                ('event_id', models.CharField(max_length=514)),
                ('return_values', django_extensions.db.fields.json.JSONField(default=dict)),
                ('event_name', models.CharField(max_length=514)),
                ('signature', models.CharField(max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('raw', django_extensions.db.fields.json.JSONField(default=dict)),
                ('contract_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eth.ContractReceipt')),
            ],
        ),
        migrations.CreateModel(
            name='EventListener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_id', models.CharField(max_length=36)),
                ('contract_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eth.ContractReceipt')),
                ('listener_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contractreceipt',
            unique_together={('transaction_hash', 'transaction_index')},
        ),
    ]
