# Generated by Django 2.2.4 on 2019-10-02 17:25

import apps.eth.fields
import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0001_squashed_091919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreceipt',
            name='block_hash',
            field=apps.eth.fields.HashField(default='', max_length=66, null=True, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')]),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='block_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='cumulative_gas_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='gas_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='logs',
            field=django_extensions.db.fields.json.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
