# Generated by Django 2.0.7 on 2018-08-29 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180801_1626'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('eth', '0002_optional_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contract_receipt',
        ),
        migrations.CreateModel(
            name='EthAction',
            fields=[
                ('transaction_hash', models.CharField(max_length=66, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EthListener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.DeleteModel(
            name='ContractReceipt',
        ),
        migrations.RemoveField(
            model_name='eventlistener',
            name='contract_receipt',
        ),
        migrations.RemoveField(
            model_name='eventlistener',
            name='listener_type',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('eth_action', models.OneToOneField(db_column='hash', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eth.EthAction')),
                ('nonce', models.IntegerField()),
                ('block_hash', models.CharField(max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('block_number', models.IntegerField()),
                ('transaction_index', models.IntegerField(null=True)),
                ('from_address', models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('to_address', models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('value', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('gas_price', models.IntegerField()),
                ('input', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReceipt',
            fields=[
                ('block_hash', models.CharField(max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('block_number', models.BigIntegerField()),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('cumulative_gas_used', models.IntegerField()),
                ('from_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('gas_used', models.IntegerField()),
                ('logs', django_extensions.db.fields.json.JSONField(default=dict)),
                ('logs_bloom', models.CharField(max_length=514)),
                ('status', models.BooleanField()),
                ('to_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('eth_action', models.OneToOneField(db_column='transaction_hash', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eth.EthAction')),
                ('transaction_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EventListener',
        ),
        migrations.AddField(
            model_name='ethlistener',
            name='eth_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eth.EthAction'),
        ),
        migrations.AddField(
            model_name='ethlistener',
            name='listener_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='ethaction',
            name='async_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.AsyncJob'),
        ),
        migrations.AddField(
            model_name='event',
            name='eth_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eth.EthAction'),
        ),
    ]
