# Generated by Django 2.0.7 on 2018-08-30 13:52

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eth', '0003_auto_20180829_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethaction',
            name='listeners',
            field=gm2m.fields.GM2MField('shipments.Shipment', through='eth.EthListener', through_fields=['eth_action', 'listener', 'listener_type', 'listener_id']),
        ),
    ]
