# Generated by Django 2.0.7 on 2018-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0004_ethaction_listeners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='input',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='block_hash',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='block_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_index',
        ),
        migrations.AddField(
            model_name='transaction',
            name='chain_id',
            field=models.IntegerField(default=1337),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas_price',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nonce',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(max_length=32),
        ),
    ]
