# Generated by Django 3.0.8 on 2020-09-01 14:09

import apps.eth.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0004_event_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceipt',
            name='evm_hash',
            field=apps.eth.fields.HashField(default='', max_length=66, null=True, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')]),
        ),
    ]
