# Generated by Django 2.0.7 on 2018-08-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0005_auto_20180830_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='gas',
            new_name='gas_limit',
        ),
    ]
