# Generated by Django 2.1.7 on 2019-06-20 19:49

import django.db.models.deletion
import gm2m.fields
from django.db import migrations, models
from gm2m.deletion import DO_NOTHING


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0037_set_initial_historical_objects'),
        ('eth', '0008_loom_tx_hash_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethaction',
            name='listeners',
            field=gm2m.fields.GM2MField('shipments.Shipment', through='eth.EthListener', through_fields=['eth_action', 'listener', 'listener_type', 'listener_id'], null=True, on_delete=DO_NOTHING),
        ),
        migrations.AddField(
            model_name='ethaction',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment', null=True, default=None),
            preserve_default=False,
        ),
    ]
