version: '3.4'
services:

  minio:
    image: minio/minio
    ports:
    - "9090:9000"
    expose:
      - '9000'
    environment:
    - MINIO_ACCESS_KEY=TEST-DEV-KEY
    - MINIO_SECRET_KEY=NON-TRIVIAL-SECRETKEY
    - MINIO_DOMAIN=minio
    command: server /data --address minio:9000

  redis_db:
    image: redis
    expose:
      - '6379'
    command: >
      --requirepass redis_pass --appendonly yes

  psql:
    ports:
      - "5432:5432"
    image: shipchain/postgis:9.6-2.4
    environment:
      - POSTGRES_USER=transmission
      - POSTGRES_PASS=transmission
      - POSTGRES_HOST=psql
      - POSTGRES_DBNAME=transmission
      - ALLOW_IP_RANGE=0.0.0.0/0

  runserver:
    build:
      context: ../
      target: local
    image: transmission-django-dev
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - transmission-runserver
      portal:
        aliases:
          - transmission-runserver
    links:
      - psql
      - redis_db
      - minio
    volumes:
      - ../:/app
      - ./django/pip.cache:/build/pip.volume
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - ENV
      - SECRET_KEY
      - SERVICE=runserver
      - REDIS_URL
      - ENGINE_RPC_URL
      - INTERNAL_URL
      - PROFILES_URL
      - ELASTICSEARCH_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - LOG_LEVEL
      - FORCE_DEBUG

networks:
  portal:
    external: true
