version: '3.6'
services:

  minio:
    expose:
      - '9000'
    networks:
      - portal

  redis_db:
    image: circleci/redis:alpine
    networks:
      - portal
    tmpfs:
      - /data
    command: >
      --requirepass redis_pass

  psql:
    image: circleci/postgres:11.1-alpine-postgis-ram
    tmpfs:
      - /dev/shm/pgdata/data
    expose:
      - '5432'
    networks:
      - portal
    environment:
      - POSTGRES_USER=transmission
      - POSTGRES_PASS=transmission
      - POSTGRES_HOST=psql
      - POSTGRES_DB=transmission
      - ALLOW_IP_RANGE=0.0.0.0/0

  runserver:
    build:
      context: ../
      target: test
    image: transmission-django-test
    command: sh -c 'while sleep 3600; do :; done'
    networks:
      - portal
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - ENV
      - SECRET_KEY
      - SERVICE=circleci
      - REDIS_URL=redis://:redis_pass@redis_db:6379/1
      - AWS_ACCESS_KEY_ID=TEST-DEV-KEY
      - AWS_SECRET_ACCESS_KEY=NON-TRIVIAL-SECRETKEY

networks:
  portal:
    driver: bridge
