resource:
  properties:
    type:
      example: Sensor

attributes:
  allOf:
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/modifiedAt'
  - $ref: '#/sensor/name'
  - $ref: '#/sensor/hardwareId'
  - $ref: '#/sensor/units'

relationships:
  type: object
  description: Relations for this resource
  allOf:
    - $ref: '#/relatedDevice'

meta:
  type: object
  description: Meta details for this resource
  properties:
    dimensionality:
      type: string
      example: "[length] * [mass] / [time] ** 2"
      description: The basic physical dimension the sensor is reporting data for.  E.G.  length, mass, time, current, temperature, amount of substance.
    base_units:
      type: string
      example: "kilogram * meter / second ** 2"
      description: The base units reported in the telemetry data
    type:
      type: string
      example: "force"
      description: The type of data reported by the sensor

relatedDevice:
  title: device
  type: object
  description: Device associated with this sensor
  properties:
    device:
      $ref: '#/device/relatedDevice'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'
      relationships:
        $ref: '#/relationships'
      meta:
        $ref: '#/meta'

getResponse:
  title: Default Sensor retrieval
  allOf:
  - $ref: '#/jsonApi/data'
  - properties:
      data:
        $ref: '#/getResource'

listResponse:
  title: Default Sensor List
  allOf:
  - $ref: '#/jsonApi/dataArray'
  - $ref: '#/jsonApi/linksAndMeta'
  - properties:
      data:
        items:
          $ref: '#/getResource'

dataTypes:
  $ref: ../core/dataTypes.yaml

device:
  $ref: ../devices/schema.yaml

sensor:
  $ref: dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
