path:
  required: true
  name: access_request_id
  in: path
  description: ID of the AccessRequest
  schema:
    $ref: '#/dataTypes/uuid'

ordering:
  name: ordering
  in: query
  description: Ordering of the objects. Default is descending order, add a `-` symbol before the variable to make it ascending.
  required: false
  schema:
    type: string
    enum: [created_at, -created_at, approved_at, -approved_at]
    example: created_at

requesterId:
  required: false
  name: requester_id
  in: query
  description: ID of the access request requester
  schema:
    $ref: '#/dataTypes/uuid'

approved:
  required: false
  name: approved
  in: query
  description: ID of the access request requester
  schema:
    type: boolean
    example: true

approvedBy:
  required: false
  name: approved_by
  in: query
  description: ID of the access request approver
  schema:
    $ref: '#/dataTypes/uuid'

dataTypes:
  $ref: ../core/dataTypes.yaml
