# Generated by Django 2.0.7 on 2018-07-16 17:40

import apps.utils
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=apps.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}')])),
                ('fax_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.CharField(default=apps.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=36)),
                ('carrier_scac', models.CharField(max_length=255)),
                ('forwarder_scac', models.CharField(max_length=255)),
                ('nvocc_scac', models.CharField(max_length=255)),
                ('shipper_reference', models.CharField(max_length=255)),
                ('forwarder_reference', models.CharField(max_length=255)),
                ('forwarders_shipper_id', models.CharField(max_length=255)),
                ('carrier_instructions', models.CharField(max_length=255)),
                ('pro_number', models.CharField(max_length=255)),
                ('master_bill', models.CharField(max_length=255)),
                ('house_bill', models.CharField(max_length=255)),
                ('subhouse_bill', models.CharField(max_length=255)),
                ('freight_payment_terms', models.CharField(max_length=255)),
                ('vessel_name', models.CharField(max_length=255)),
                ('voyage_number', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('number_of_packages', models.IntegerField(default=0)),
                ('gross_weight_kgs', models.IntegerField(default=0)),
                ('volume_cbms', models.IntegerField(default=0)),
                ('container_count', models.IntegerField(default=0)),
                ('dimensional_weight', models.IntegerField(default=0)),
                ('chargeable_weight', models.IntegerField(default=0)),
                ('docs_received_actual', models.DateTimeField()),
                ('docs_approved_actual', models.DateTimeField()),
                ('pickup_appointment_actual', models.DateTimeField()),
                ('pickup_estimated', models.DateTimeField()),
                ('pickup_actual', models.DateTimeField()),
                ('loading_estimated', models.DateTimeField()),
                ('loading_actual', models.DateTimeField()),
                ('departure_estimated', models.DateTimeField()),
                ('departure_actual', models.DateTimeField()),
                ('delivery_appointment_actual', models.DateTimeField()),
                ('arrival_port_estimated', models.DateTimeField()),
                ('arrival_port_actual', models.DateTimeField()),
                ('delivery_estimated', models.DateTimeField()),
                ('delivery_actual', models.DateTimeField()),
                ('last_attempted_delivery_actual', models.DateTimeField()),
                ('cancel_requested_date_actual', models.DateTimeField()),
                ('cancel_confirmed_date_actual', models.DateTimeField()),
                ('customs_filed_date_actual', models.DateTimeField()),
                ('customs_hold_date_actual', models.DateTimeField()),
                ('customs_release_date_actual', models.DateTimeField()),
                ('containerization_type', models.CharField(max_length=255)),
                ('arrival_unlocode', models.CharField(max_length=255)),
                ('final_port_unlocode', models.CharField(max_length=255)),
                ('import_unlocode', models.CharField(max_length=255)),
                ('lading_unlocode', models.CharField(max_length=255)),
                ('origin_unlocode', models.CharField(max_length=255)),
                ('us_routed_export', models.CharField(max_length=255)),
                ('import_customs_mode', models.CharField(max_length=255)),
                ('us_customs_export_port', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('final_destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_shipments_dest', to='shipments.Location')),
                ('ship_from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_shipments_from', to='shipments.Location')),
                ('ship_to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_shipments_to', to='shipments.Location')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
