# Generated by Django 2.0.7 on 2018-07-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20180716_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
