# Generated by Django 2.2.4 on 2019-10-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_hash_rate_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='asset_custodian_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='asset_physical_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='asset_custodian_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='asset_physical_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='version',
            field=models.CharField(default='1.2.2', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='version',
            field=models.CharField(default='1.2.2', max_length=255),
        ),
    ]
