# Generated by Django 2.2.4 on 2019-11-21 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_add_asset_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='geofences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='shipment',
            name='geofences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36, null=True), blank=True, null=True, size=None),
        ),
    ]
