# Generated by Django 2.2.4 on 2019-11-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_exception_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipment',
            name='bill_to_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_bill', to='shipments.HistoricalLocation'),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shipments.Device'),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='final_destination_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_dest', to='shipments.HistoricalLocation'),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='ship_from_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_from', to='shipments.HistoricalLocation'),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='ship_to_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_to', to='shipments.HistoricalLocation'),
        ),
    ]
