# Generated by Django 2.0.7 on 2018-08-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20180808_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadshipment',
            name='contract_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='end_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='escrow_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='escrow_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='moderator',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='paid_tokens',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment_accepted_by_shipper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment_canceled_by_shipper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment_committed_by_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment_completed_by_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='start_block',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
