# Generated by Django 2.0.7 on 2018-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadshipment',
            name='commitment_confirmed_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
