# Generated by Django 2.2.7 on 2019-12-06 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shipchain_common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0006_add_geofences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentNote',
            fields=[
                ('id', models.CharField(default=shipchain_common.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('message', models.TextField(validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.MinLengthValidator(1)])),
                ('author_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
