# Generated by Django 2.0.7 on 2018-08-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_more_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='contract_version',
            field=models.CharField(default='1.0.2', max_length=36),
            preserve_default=False,
        ),
    ]
