# Generated by Django 2.2.7 on 2020-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='assignee_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='assignee_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='version',
            field=models.CharField(default='1.2.3', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='version',
            field=models.CharField(default='1.2.3', max_length=255),
        ),
    ]
