# Generated by Django 2.2.7 on 2020-02-07 20:34

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_notes'),
    ]

    operations = [

        HStoreExtension(),

        migrations.AlterField(
            model_name='historicalshipment',
            name='version',
            field=models.CharField(default='1.2.3', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='version',
            field=models.CharField(default='1.2.3', max_length=255),
        ),
        migrations.CreateModel(
            name='ShipmentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('definition', django.contrib.postgres.fields.hstore.HStoreField(validators=[django.contrib.postgres.validators.KeysValidator(keys=('type', 'value'), strict=True)])),
                ('user_id',models.UUIDField(null=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment', related_name='shipment_tags')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
