# Generated by Django 2.0.7 on 2018-08-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_contract_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='load_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.LoadShipment'),
        ),
    ]
