# Generated by Django 2.0.7 on 2018-08-30 21:37

import apps.shipments.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_auto_20180830_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadshipment',
            name='escrow_status',
            field=enumfields.fields.EnumField(default=1, enum=apps.shipments.models.EscrowStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='funding_type',
            field=enumfields.fields.EnumField(default=2, enum=apps.shipments.models.FundingType, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='shipment_status',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.ShipmentStatus, max_length=10),
        ),
    ]
