# Generated by Django 2.0.7 on 2018-08-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_auto_20180904_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='owner_id',
            field=models.CharField(null=False, max_length=36),
            preserve_default=False,
        ),
    ]