# Generated by Django 2.0.7 on 2018-09-10 19:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_location_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='final_destination_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_dest', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_from_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_to_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='shipments.Location'),
        ),
    ]
