# Generated by Django 2.2.12 on 2020-04-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_telemetrydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
