# Generated by Django 2.0.7 on 2018-09-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_auto_20180911_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='load_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.LoadShipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.Device'),
        ),
    ]
