# Generated by Django 2.0.7 on 2018-09-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_auto_20180914_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadshipment',
            name='vault_hash',
            field=models.CharField(max_length=66, null=True),
        ),
    ]
