# Generated by Django 2.0.9 on 2018-11-15 19:16

import apps.eth.fields
import apps.shipments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_loadshipment_vault_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadShipmentEth',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shipments.Shipment')),
                ('shipper', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('carrier', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('moderator', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('shipment_state', enumfields.fields.EnumField(default=0, enum=apps.shipments.models.ShipmentState, max_length=10)),
                ('contracted_amount', models.IntegerField(default=0)),
                ('funded_amount', models.IntegerField(default=0)),
                ('created_at', models.IntegerField(default=0)),
                ('funding_type', enumfields.fields.EnumField(default=0, enum=apps.shipments.models.FundingType, max_length=10)),
                ('escrow_state', enumfields.fields.EnumField(default=0, enum=apps.shipments.models.EscrowState, max_length=10)),
                ('refund_address', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('vault_hash', apps.eth.fields.HashField(default='', max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('vault_uri', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadShipmentTxm',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shipments.Shipment')),
                ('shipper', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('carrier', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('moderator', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('shipment_state', enumfields.fields.EnumField(default=0, enum=apps.shipments.models.ShipmentState, max_length=10)),
                ('contracted_amount', models.IntegerField(default=0)),
                ('funded_amount', models.IntegerField(default=0)),
                ('created_at', models.IntegerField(default=0)),
                ('funding_type', enumfields.fields.EnumField(default=0, enum=apps.shipments.models.FundingType, max_length=10)),
                ('escrow_state', enumfields.fields.EnumField(default=0, enum=apps.shipments.models.EscrowState, max_length=10)),
                ('refund_address', apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')])),
                ('vault_hash', apps.eth.fields.HashField(default='', max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')])),
                ('vault_uri', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='load_data',
        ),
        migrations.DeleteModel(
            name='LoadShipment',
        ),
    ]
