# Generated by Django 2.0.9 on 2018-11-19 19:53

import apps.eth.fields
import apps.shipments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


def delete_all_loadshipments(apps, schema_editor):
    LoadShipment = apps.get_model('shipments', 'LoadShipment')
    LoadShipment.objects.all().delete()


def create_default_loadshipments(apps, schema_editor):
    Shipment = apps.get_model('shipments', 'Shipment')

    from django.db.models.signals import post_save
    from apps.shipments.models import LoadShipment
    from apps.shipments.signals import loadshipment_post_save
    post_save.disconnect(loadshipment_post_save, sender=LoadShipment, dispatch_uid='loadshipment_post_save')
    for shipment in Shipment.objects.all().iterator():
        LoadShipment.objects.create(shipment_id=shipment.id)
    post_save.connect(loadshipment_post_save, sender=LoadShipment, dispatch_uid='loadshipment_post_save')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('shipments', '0015_loadshipment_vault_hash'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RemoveField(
            model_name='shipment',
            name='load_data',
        ),
        migrations.RunPython(delete_all_loadshipments, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='loadshipment',
            old_name='paid_amount',
            new_name='funded_amount',
        ),
        migrations.RenameField(
            model_name='loadshipment',
            old_name='shipment_status',
            new_name='shipment_state',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='commitment_confirmed_date',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='contract_funded',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='end_block',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='escrow_funded',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='escrow_paid',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='escrow_status',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='paid_tokens',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_accepted_by_shipper',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_amount',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_canceled_by_shipper',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_committed_by_carrier',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_completed_by_carrier',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_created',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='start_block',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='contracted_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='escrow_state',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.EscrowState, max_length=10),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='refund_address',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='vault_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='carrier',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='funding_type',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.FundingType, max_length=10),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='moderator',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipper',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='vault_hash',
            field=apps.eth.fields.HashField(default='', max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')]),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='shipment',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                       serialize=False, to='shipments.Shipment'),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_loadshipments, migrations.RunPython.noop, atomic=False),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                       serialize=False, to='shipments.Shipment'),
            preserve_default=False,
        ),
        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
