# Generated by Django 2.0.9 on 2018-11-19 19:53

import apps.eth.fields
import apps.shipments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_loadshipment_vault_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadshipment',
            old_name='paid_amount',
            new_name='funded_amount',
        ),
        migrations.RenameField(
            model_name='loadshipment',
            old_name='shipment_status',
            new_name='shipment_state',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='commitment_confirmed_date',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='contract_funded',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='end_block',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='escrow_funded',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='escrow_paid',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='escrow_status',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='paid_tokens',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_accepted_by_shipper',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_amount',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_canceled_by_shipper',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_committed_by_carrier',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_completed_by_carrier',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_created',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='start_block',
        ),
        migrations.RemoveField(
            model_name='loadshipment',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='load_data',
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='contracted_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='escrow_state',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.EscrowState, max_length=10),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='refund_address',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='shipment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shipments.Shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadshipment',
            name='vault_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='carrier',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='funding_type',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.FundingType, max_length=10),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='moderator',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='shipper',
            field=apps.eth.fields.AddressField(default='0x0', max_length=42, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^0x([A-Fa-f0-9]{40})$')]),
        ),
        migrations.AlterField(
            model_name='loadshipment',
            name='vault_hash',
            field=apps.eth.fields.HashField(default='', max_length=66, validators=[django.core.validators.RegexValidator(message='Invalid hash.', regex='^0x([A-Fa-f0-9]{64})$')]),
        ),
    ]
