# Generated by Django 2.2.12 on 2020-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_gtx_validation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='arrival_est',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='arrival_est',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
