# Generated by Django 2.2.12 on 2020-04-29 14:15

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_gtx_validation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipment',
            name='carrier_wallet_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='moderator_wallet_id',
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='shipper_wallet_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='state',
            field=django_fsm.FSMIntegerField(db_index=True, default=10, protected=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier_wallet_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='moderator_wallet_id',
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_wallet_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=django_fsm.FSMIntegerField(db_index=True, default=10, protected=True),
        ),
    ]
