# Generated by Django 2.0.9 on 2018-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_loadshipment_110'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='moderator_wallet_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
