# Generated by Django 3.0.8 on 2020-08-27 23:21

import apps.shipments.models.access_request
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_carrier_abv'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester_id', models.UUIDField(editable=False)),
                ('shipment_permission', enumfields.fields.EnumIntegerField(default=1, enum=apps.shipments.models.access_request.PermissionLevel)),
                ('tags_permission', enumfields.fields.EnumIntegerField(default=1, enum=apps.shipments.models.access_request.PermissionLevel)),
                ('documents_permission', enumfields.fields.EnumIntegerField(default=1, enum=apps.shipments.models.access_request.PermissionLevel)),
                ('notes_permission', enumfields.fields.EnumIntegerField(default=1, enum=apps.shipments.models.access_request.PermissionLevel)),
                ('tracking_permission', enumfields.fields.EnumIntegerField(default=1, enum=apps.shipments.models.access_request.PermissionLevel)),
                ('telemetry_permission', enumfields.fields.EnumIntegerField(default=1, enum=apps.shipments.models.access_request.PermissionLevel)),
                ('approved', models.NullBooleanField(default=None)),
                ('approved_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('approved_by', models.UUIDField(default=None, editable=False, null=True)),
                ('shipment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
