# Generated by Django 2.1.4 on 2018-12-18 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_rename_shipment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='version',
            field=models.CharField(default='1.1.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='altitude',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='speed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='uncertainty',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
