# Generated by Django 2.0.10 on 2019-01-21 21:31

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.shipments.migrations.0024_trackingdata_point_data_migration


def set_tracking_data_point_field(apps, schema_editor):
    """
    Populate the new TrackingData.point field with model values
    """
    trackingdata = apps.get_model('shipments', 'TrackingData')

    for data in trackingdata.objects.all():
        data.point = Point(data.longitude, data.latitude)


class Migration(migrations.Migration):

    replaces = [('shipments', '0022_shipment_route_jsonfield'), ('shipments', '0023_remove_shipment_route_jsonfield'), ('shipments', '0024_trackingdata_point_data_migration')]

    dependencies = [
        ('shipments', '0021_change_unrequired_TD_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingdata',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='point',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.RunPython(
            code=set_tracking_data_point_field,
        ),
    ]
