# Generated by Django 2.0.10 on 2019-01-16 20:39

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0021_change_unrequired_TD_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingdata',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='shipment',
            name='route_as_line',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='route_as_point',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='point',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
