# Generated by Django 2.0.10 on 2019-01-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0022_shipment_route_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='route_as_line',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='route_as_point',
        ),
    ]
