# Generated by Django 2.1.5 on 2019-01-22 19:29

import apps.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_trackingdata_point_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLink',
            fields=[
                ('id', models.CharField(default=apps.utils.random_id, max_length=36,
                                        primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
