# Generated by Django 2.0.10 on 2019-01-18 19:44

from django.db import migrations
from django.contrib.gis.geos import Point


def set_tracking_data_point_field(apps, schema_editor):
    """
    Populate the new TrackingData.point field with model values
    """
    trackingdata = apps.get_model('shipments', 'TrackingData')

    for data in trackingdata.objects.all():
        data.point = Point(data.longitude, data.latitude)


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_remove_shipment_route_jsonfield'),
    ]

    operations = [
        migrations.RunPython(set_tracking_data_point_field),
    ]
