# Generated by Django 2.1.5 on 2019-02-11 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_permissionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_hazmat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_master_bol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='nmfc_class',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[
                django.core.validators.RegexValidator(message='Invalid nmfc class number.',
                                                      regex='^1[015]0$|^1[27]5$|^2[05]0$|^[345]00$|^[567]0$|^[568]5$|^92\\.5$|^77\\.5$')]),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seal_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='bill_to_location',
            field=models.ForeignKey(null=True, on_delete=models.deletion.PROTECT, related_name='bill_to',
                                    to='shipments.Location'),
        ),
    ]
