# Generated by Django 2.1.5 on 2019-01-22 19:29

from django.db import migrations


def reverse_geometry(apps, schema_editor):
    Location = apps.get_model("shipments", "Location")

    for location in Location.objects.all():
        if location.geometry:
            x = location.geometry.x
            y = location.geometry.y
            location.geometry.y = x
            location.geometry.x = y
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_permissionlink'),
    ]

    operations = [
        migrations.RunPython(reverse_geometry),
    ]
