# Generated by Django 2.1.5 on 2019-02-27 20:02

import apps.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0024_permissionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.CharField(db_index=True, max_length=36)),
                ('certificate_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShipment',
            fields=[
                ('id', models.CharField(db_index=True, default=apps.utils.random_id, max_length=36)),
                ('owner_id', models.CharField(max_length=36)),
                ('storage_credentials_id', models.CharField(max_length=36)),
                ('vault_id', models.CharField(max_length=36, null=True)),
                ('vault_uri', models.CharField(max_length=255, null=True)),
                ('shipper_wallet_id', models.CharField(max_length=36)),
                ('carrier_wallet_id', models.CharField(max_length=36)),
                ('moderator_wallet_id', models.CharField(max_length=36, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('contract_version', models.CharField(max_length=36)),
                ('carriers_scac', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarders_scac', models.CharField(blank=True, max_length=255, null=True)),
                ('nvocc_scac', models.CharField(blank=True, max_length=255, null=True)),
                ('shippers_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarders_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarders_shipper_id', models.CharField(blank=True, max_length=255, null=True)),
                ('carriers_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_master', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_house', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_subhouse', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('vessel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('voyage_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_transport_code', models.CharField(blank=True, max_length=255, null=True)),
                ('package_qty', models.IntegerField(blank=True, null=True)),
                ('weight_gross', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('container_qty', models.IntegerField(blank=True, null=True)),
                ('weight_dim', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('weight_chargeable', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('docs_received_act', models.DateTimeField(blank=True, null=True)),
                ('docs_approved_act', models.DateTimeField(blank=True, null=True)),
                ('pickup_appt', models.DateTimeField(blank=True, null=True)),
                ('pickup_est', models.DateTimeField(blank=True, null=True)),
                ('pickup_act', models.DateTimeField(blank=True, null=True)),
                ('loading_est', models.DateTimeField(blank=True, null=True)),
                ('loading_act', models.DateTimeField(blank=True, null=True)),
                ('departure_est', models.DateTimeField(blank=True, null=True)),
                ('departure_act', models.DateTimeField(blank=True, null=True)),
                ('delivery_appt_act', models.DateTimeField(blank=True, null=True)),
                ('port_arrival_est', models.DateTimeField(blank=True, null=True)),
                ('port_arrival_act', models.DateTimeField(blank=True, null=True)),
                ('delivery_est', models.DateTimeField(blank=True, null=True)),
                ('delivery_act', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempt', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_date_act', models.DateTimeField(blank=True, null=True)),
                ('cancel_confirmed_date_act', models.DateTimeField(blank=True, null=True)),
                ('customs_filed_date_act', models.DateTimeField(blank=True, null=True)),
                ('customs_hold_date_act', models.DateTimeField(blank=True, null=True)),
                ('customs_release_date_act', models.DateTimeField(blank=True, null=True)),
                ('container_type', models.CharField(blank=True, max_length=255, null=True)),
                ('port_arrival_locode', models.CharField(blank=True, max_length=255, null=True)),
                ('final_port_locode', models.CharField(blank=True, max_length=255, null=True)),
                ('import_locode', models.CharField(blank=True, max_length=255, null=True)),
                ('lading_locode', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_locode', models.CharField(blank=True, max_length=255, null=True)),
                ('us_routed', models.CharField(blank=True, max_length=255, null=True)),
                ('import_customs_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('us_export_port', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(default='1.1.0', max_length=255)),
                ('customer_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.Device')),
                ('final_destination_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.Location')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ship_from_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.Location')),
                ('ship_to_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.Location')),
            ],
            options={
                'verbose_name': 'historical shipment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDevice',
        ),
    ]
