# Generated by Django 2.1.5 on 2019-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_permissionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_hazmat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_master_bol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='nmfc_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='nmfc_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seal_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='bill_to_location',
            field=models.ForeignKey(null=True, on_delete=models.deletion.PROTECT, related_name='bill_to',
                                    to='shipments.Location'),
        ),
    ]
