# Generated by Django 2.1.5 on 2019-01-30 16:56

from django.db import migrations


def set_location_country(apps, schema_editor):
    """
    Picks the first two characters of the field Location.country and set it as value
    """
    locations = apps.get_model('shipments', 'Location')

    for location in locations.objects.all():
        country = location.country
        if country:
            location.country = country.upper()[:2]
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_permissionlink'),
    ]

    operations = [
        migrations.RunPython(
            code=set_location_country,
        ),
    ]
