# Generated by Django 2.1.5 on 2019-02-04 21:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('shipments', '0026_set_location_country_max_length'), ('shipments', '0027_shipment_locations_to_one_to_one_field'), ('shipments', '0028_alter_shipment_location_definition')]

    dependencies = [
        ('shipments', '0025_location_country_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Invalid country code.', regex='^A[^ABCHJKNPVY]|B[^CKPUX]|C[^BEJPQST]|D[EJKMOZ]|E[CEGHRST]|F[IJKMOR]|G[^CJKOVXZ]|H[KMNRTU]|I[DEL-OQ-T]|J[EMOP]|K[EGHIMNPRWYZ]|L[ABCIKR-VY]|M[^BIJ]|N[ACEFGILOPRUZ]|OM|P[AE-HK-NRSTWY]|QA|R[EOSUW]|S[^FPQUW]|T[^ABEIPQSUXY]|U[AGMSYZ]|V[ACEGINU]|WF|WS|YE|YT|Z[AMW]')]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='final_destination_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_dest', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_from_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_from', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_to_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_to', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='final_destination_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_dest', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_from_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='shipments.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_to_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='shipments.Location'),
        ),
    ]
