# Generated by Django 2.1.5 on 2019-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0027_shipment_device_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='us_routed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='version',
            field=models.CharField(default='1.2.0', max_length=255),
        ),
    ]
