# Generated by Django 2.1.5 on 2019-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0028_update_model_for_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='is_hazmat',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='is_master_bol',
            field=models.NullBooleanField(),
        ),
    ]
