# Generated by Django 2.1.5 on 2019-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0029_nullable_booleans'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='updated_by',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
