# Generated by Django 2.1.7 on 2019-03-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0029_nullable_booleans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingdata',
            old_name='device_id',
            new_name='device',
        ),
    ]
