# Generated by Django 2.1.7 on 2019-03-21 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def enforce_unique_locations(apps, schema_editor):
    existing_locations_seen = set()
    Shipment = apps.get_model('shipments', 'Shipment')
    for shipment in Shipment.objects.all():
        if shipment.ship_from_location_id:
            if shipment.ship_from_location_id in existing_locations_seen:
                shipment.ship_from_location.pk = None
                shipment.ship_from_location.id = None
                shipment.ship_from_location.save()
                Shipment.objects.filter(id=shipment.id).update(ship_from_location_id=shipment.ship_from_location.id)
            existing_locations_seen.add(shipment.ship_from_location.id)

        if shipment.ship_to_location_id:
            if shipment.ship_to_location_id in existing_locations_seen:
                shipment.ship_to_location.pk = None
                shipment.ship_to_location.id = None
                shipment.ship_to_location.save()
                Shipment.objects.filter(id=shipment.id).update(ship_to_location_id=shipment.ship_to_location.id)
            existing_locations_seen.add(shipment.ship_to_location.id)

        if shipment.final_destination_location_id:
            if shipment.final_destination_location_id in existing_locations_seen:
                shipment.final_destination_location.pk = None
                shipment.final_destination_location.id = None
                shipment.final_destination_location.save()
                Shipment.objects.filter(id=shipment.id).update(final_destination_location_id=shipment.final_destination_location.id)
            existing_locations_seen.add(shipment.final_destination_location.id)

        if shipment.bill_to_location_id:
            if shipment.bill_to_location_id in existing_locations_seen:
                shipment.bill_to_location.pk = None
                shipment.bill_to_location.id = None
                shipment.bill_to_location.save()
                Shipment.objects.filter(id=shipment.id).update(bill_to_location_id=shipment.bill_to_location.id)
            existing_locations_seen.add(shipment.bill_to_location.id)


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0032_location_country_data_migration'),
    ]

    operations = [
        migrations.RunPython(enforce_unique_locations),
    ]
