# Generated by Django 2.1.7 on 2019-04-10 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0034_alter_shipment_location_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdata',
            name='speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
