# Generated by Django 2.1.7 on 2019-05-08 18:01

from django.db import migrations
from apps.simple_history import TxmHistoricalRecords
from apps.shipments.models import Shipment, Location


def set_initial_historical(apps, schema_editor):
    """
    Create an initial  HistoricalShipment, HistoricalLocation
    object for every shipment, location respectively with a null history_user
    """
    def create_historical_instance(obj):
        TxmHistoricalRecords().create_historical_record(obj, '~')
        h_instance = obj.history.first()
        h_instance.history_user = None
        h_instance.updated_by = None
        h_instance.save()

    for location in Location.objects.all():
        create_historical_instance(location)

    for shipment in Shipment.objects.all():
        create_historical_instance(shipment)


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0036_historicallocation_historicalshipment'),
    ]

    operations = [
        migrations.RunPython(
            code=set_initial_historical,
        ),
    ]
