# Generated by Django 2.1.7 on 2019-05-08 18:01

from django.db import migrations
from apps.shipments.models import Shipment, Location


def set_initial_historical(apps, schema_editor):
    """
    Create an initial  HistoricalShipment, HistoricalLocation
    object for every shipment, location respectively with a null history_user
    """

    for location in Location.objects.all():
        Shipment.anonymous_historical_change(dtm=True, initial_object=location)

    for shipment in Shipment.objects.all():
        Shipment.anonymous_historical_change(dtm=True, initial_object=shipment)


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0036_historicallocation_historicalshipment'),
    ]

    operations = [
        migrations.RunPython(
            code=set_initial_historical,
        ),
    ]
