# Generated by Django 2.1.7 on 2019-07-10 17:55

import apps.shipments.models
from django.db import migrations, models
import django_fsm
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0037_set_initial_historical_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='delayed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='exception',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.ExceptionType, max_length=10),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='expected_delay_hours',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='state',
            field=django_fsm.FSMIntegerField(default=10, protected=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delayed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='exception',
            field=enumfields.fields.EnumField(default=0, enum=apps.shipments.models.ExceptionType, max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_delay_hours',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='state',
            field=django_fsm.FSMIntegerField(default=10, protected=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='delivery_act',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='pickup_act',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='port_arrival_act',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_act',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_act',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='port_arrival_act',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
