# Generated by Django 2.2.4 on 2019-09-10 14:37

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0039_shipment_state_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='background_data_hash_interval',
            field=models.IntegerField(default=settings.DEFAULT_BACKGROUND_DATA_HASH_INTERVAL, validators=[django.core.validators.MinValueValidator(0)])
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='manual_update_hash_interval',
            field=models.IntegerField(default=settings.DEFAULT_MANUAL_UPDATE_HASH_INTERVAL, validators=[django.core.validators.MinValueValidator(0)])
        ),
        migrations.AddField(
            model_name='shipment',
            name='background_data_hash_interval',
            field=models.IntegerField(default=settings.DEFAULT_BACKGROUND_DATA_HASH_INTERVAL, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manual_update_hash_interval',
            field=models.IntegerField(default=settings.DEFAULT_MANUAL_UPDATE_HASH_INTERVAL, validators=[django.core.validators.MinValueValidator(0)])
        ),
    ]
