path:
  required: true
  name: document_id
  in: path
  description: ID of the Document
  schema:
    $ref: '#/dataTypes/uuid'

fileType:
  required: false
  in: query
  name: file_type
  description: Type of file extension to filter by
  schema:
    type: string
    enum: [PDF, JPEG, PNG]
    example: PDF

documentType:
  required: false
  in: query
  name: document_type
  description: Document category to filter by
  schema:
    type: string
    enum: [BOL, IMAGE, OTHER, COMMERCIAL_INVOICE, PROOF_OF_INSURANCE, CERTIFICATE_OF_ORIGIN, CUSTOMS_FORMS, FREIGHT_BILL, AIR_WAYBILL, PACKING_SLIP]
    example: BOL

uploadStatus:
  required: false
  in: query
  name: upload_status
  description: Upload status of the files to filter by
  schema:
    type: string
    enum: [PENDING, COMPLETE, FAILED]
    example: PENDING

search:
  required: false
  in: query
  name: search
  description: Search for documents with name/description info
  schema:
    type: string
    example: 'BOL #123'


dataTypes:
  $ref: ../core/dataTypes.yaml
