# Generated by Django 3.0.8 on 2020-10-08 22:07

import apps.imports.models
import apps.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import enumfields.fields
import shipchain_common.utils


class Migration(migrations.Migration):

    replaces = [('imports', '0001_initial'), ('imports', '0002_shipment_import_descending_order'), ('imports', '0003_owner_id_db_index')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentImport',
            fields=[
                ('id', models.CharField(default=shipchain_common.utils.random_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('storage_credentials_id', models.CharField(max_length=36)),
                ('shipper_wallet_id', models.CharField(max_length=36)),
                ('carrier_wallet_id', models.CharField(max_length=36)),
                ('owner_id', models.CharField(db_index=True, max_length=36)),
                ('masquerade_id', models.CharField(max_length=36)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('file_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.imports.models.FileType)),
                ('upload_status', enumfields.fields.EnumIntegerField(default=0, enum=apps.utils.UploadStatus)),
                ('processing_status', enumfields.fields.EnumIntegerField(default=0, enum=apps.imports.models.ProcessingStatus)),
                ('report', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
