# Generated by Django 2.2.12 on 2020-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_shipment_import_descending_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentimport',
            name='owner_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
